version: "3.9" # docker-compose.ymlのバージョンを指定

services:
  demo-app:
    build: .
    volumes:
      - .:/src # アプリケーションのソースコードのマウント
    ports:
      - "80:80"
    env_file: # .env ファイルを指定
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes: # 使用するボリュームを定義
  db-data: # dbデータ用のボリューム

